### ISSUE TITLE
Warning: Computation failed in `stat_forecast()`: All inputs to rbind.fill must be data.frames

### ISSUE THREAD

**Issue by khailper** [tidyverts/fablelite#22]
Getting an error with geom_forecast():
```
library(ggplot2)
library(tsibble)
#> 
#> Attaching package: 'tsibble'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
library(tsibbledata)
library(fable)
#> Loading required package: fablelite


tsibbledata::aus_livestock %>% 
  autoplot() + 
  guides(color = FALSE) +
  geom_forecast()
#> Plot variable not specified, automatically selected `var = Count`
#> Warning: Computation failed in `stat_forecast()`:
#> All inputs to rbind.fill must be data.frames
```

Sorry for the messy plot. It was the first internal dataset I could find that replicated the error I was seeing on internal company data. It's clearer with less paths, but the forecast geom isn't being added to the underlying plot.

**Comment by mitchelloharawild** [comment]
Thanks for the issue report! Should be fixed now.
Note that there is some discussion for how geom_forecast() should function by default: https://github.com/tidyverts/fable/issues/98

The current usage may not continue to work in the future (requiring `stat = "forecast"` to be specified.)
