### ISSUE TITLE
devtools install is failing for fablelite

### ISSUE THREAD

**Issue by ak11111** [tidyverts/fablelite#3]
devtools::install_github("tidyverts/fablelite")
...
Error: package or namespace load failed for ‘fablelite’:
 object 'is_vector_s3' not found whilst loading namespace 'fablelite'
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/fablelite’
Installation failed: Command failed (1)

I tried it on R 3.4.3 and R 3.5.1

**Comment by mitchelloharawild** [comment]
This should be fixed.
