### ISSUE TITLE
library(fablelite) gets error: 'fablelite.rdb' is corrupt

### ISSUE THREAD

**Issue by gregheth** [tidyverts/fablelite#4]
After load fablelite package from Github, library(fablelite) command gets error message "fablelite.rdb is corrupt".

Because fable has a dependency on fablelite, fable cannot be used until this error is fixed.

## Environment and Logs

> version:                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray 

> RStudio Version 1.1.383

```
> devtools::install_github("tidyverts/fablelite", force = TRUE)
Downloading GitHub repo tidyverts/fablelite@master
from URL https://api.github.com/repos/tidyverts/fablelite/zipball/master
Installing fablelite
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
 '/private/var/folders/n1/11dpffjn3r11dq0v3m1xd_zc0000gq/T/RtmpfXceZA/devtools14da36f494d26/tidyverts-fablelite-700b12c'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library' --install-tests 
* installing *source* package 'fablelite' ...
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded
* DONE (fablelite)

> library(fablelite)
Error: package or namespace load failed for ‘fablelite’ in get(method, envir = home):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/fablelite/R/fablelite.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
```

**Comment by mitchelloharawild** [comment]
This issue is an installation problem specific to your system, perhaps something happened during or after installation. This is not an issue with the fablelite package.

https://github.com/r-lib/devtools/issues/942#issuecomment-144390231
Try restarting R and reinstall the `fablelite` package.

**Comment by gregheth** [comment]
Ok thanks.  (and thank you for replying quickly) 
That is the first time for me that restarting R fixed a problem. 

FYI - Loading the fablelite package I get some invalid variable names. 
237 are valid, 6 are invalid R names.
```
[.fcdist
[.hilo
[.lst_dcmp
[.lst_fc
[.lst_mdl
$.hilo
```
This happens on separate Mac and Windows computers.

I am also getting many other errors.  Should I continue creating new issues in the fable and fablelite Github or should I give up and wait for them to become more stable?

**Comment by gregheth** [comment]
done
