### ISSUE TITLE
use `group_by` + `summarise()` instead of `nest()` + `map()` for speed

### ISSUE THREAD

**Issue by earowang** [tidyverts/fablelite#5]
https://github.com/tidyverts/fablelite/blob/744e586504f04aa7cb386a1bf7a7705c129f516e/R/multivariate.R#L22

**Comment by mitchelloharawild** [comment]
Closed as not applicable for this scenario.

**Comment by earowang** [comment]
I think you still can use `group_by()` and `summarise()`, but with `purrr::pmap()`.

```r
.data %>% 
  group_by_key() %>% 
  summarise(data = list(pmap(., as_tibble))) %>% 
  pull()
}
```

But **dplyr** starts to implement `split_by()` now.
