### ISSUE TITLE
nest() and unnest() need updating

### ISSUE THREAD

**Issue by earowang** [tidyverts/fablelite#69]
**tidyr** v1.0.0 will hit on CRAN before useR. `nest()` & `unnest()` interfaces have changed a bit. Will likely trigger warnings/messages, for example https://github.com/tidyverts/fablelite/blob/7b545ca3385f0e15e26644ddcc806e87f7d5e9d3/R/accuracy.R#L205

Please see the up-to-date docs https://tidyr.tidyverse.org/dev/reference/nest.html

**Comment by mitchelloharawild** [comment]
Big performance gains from making this change, especially. Thanks! :+1:
