### ISSUE TITLE
simplify dable()

### ISSUE THREAD

**Issue by earowang** [tidyverts/fablelite#70]
https://github.com/tidyverts/fablelite/blob/7b545ca3385f0e15e26644ddcc806e87f7d5e9d3/R/dable.R#L12

Probably `key`, `index`, and `regular` can be absorbed into `...` handled by `tsibble()`?

**Comment by mitchelloharawild** [comment]
Could be, but I wanted to be more explicit in the docs. I imagine similar can be said for `fable()`.
If you prefer keeping `tsibble` args in `...` then I'd be happy to change that.

**Comment by earowang** [comment]
I'd prefer `@param ... Arguments passed to [tsibble::tsibble()]`.
