### ISSUE TITLE
Problems installing fablelite from github using devtools

### ISSUE THREAD

**Issue by DJamesWilliamson** [tidyverts/fablelite#8]
Similar to previous install problem with namespace which I see was fixed. However ...
Trying to install fablelite on Mac:
platform       x86_64-apple-darwin15.6.0                                     
version.string R version 3.5.2 (2018-12-20) 
with error message "object 'n_keys' not found whilst loading namespace 'fablelite'":
> devtools::install_github("tidyverts/fablelite")
Downloading GitHub repo tidyverts/fablelite@master
✔  checking for file ‘/private/var/folders/ks/x4lpc3qx7jj2h0vxd3ppqrsw0000gn/T/Rtmp7NlNge/remotes6f14bc40af6/tidyverts-fablelite-87cdee8/DESCRIPTION’ ...
─  preparing ‘fablelite’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘fablelite_0.0.0.9100.tar.gz’
   
* installing *source* package ‘fablelite’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘fablelite’:
 object 'n_keys' not found whilst loading namespace 'fablelite'
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/fablelite’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/ks/x4lpc3qx7jj2h0vxd3ppqrsw0000gn/T//Rtmp7NlNge/file6f13d5b53be/fablelite_0.0.0.9100.tar.gz’ had non-zero exit status

**Comment by earowang** [comment]
As the development version of **tsibble** is undergoing some changes, can you please have tsibble `v0.6.2` installed and try to re-install **fablelite**?

**Comment by DJamesWilliamson** [comment]
Many thanks Earo, that seems to work. I have been trying to follow along with the YouTube presentations you, Rob and Mitchell have recently posted. Quick follow up question: how do I display the model fit? What verb is required before fbl_cafe_fit below? The second formulation prints out what I want (ie summary) but summary(fbl_cafe_fit) doesn't seem to work (also tried print and glance). I thought this might have been due to my inability to install fablelite.
fbl_cafe_fit <- vic_cafe %>%
    fable::ETS(log(Turnover) ~ season("A"))
summary(fbl_cafe_fit)

Length  Class   Mode 
     0   NULL   NULL


vic_cafe %>%
    model(ETS(log(Turnover) ~ season("A"))) %>%
    summary


  Smoothing parameters:
    alpha = 0.5826887 
    beta  = 0.0001120739 
    gamma = 0.0001069139 

  Initial states: ...... etc


Sorry to impose on you,
James
    On Monday, 28 January 2019, 2:12:05 pm AWST, Earo Wang <notifications@github.com> wrote:  
 
 
As the development version of tsibble is undergoing some changes, can you please have tsibble v0.6.2 installed and try to re-install fablelite?

**Comment by earowang** [comment]
The former code no longer works (since `ETS()` doesn't accept data), and the latter is the newly revised API for modelling. Please see my recent rstudio conference slides http://slides.earo.me/rstudioconf19/ for new forecasting API.
