### ISSUE TITLE
Partial feature tagging

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/fablelite#82]
@earowang 

Some features like `features_stl` return elements of different tags ("trend" and "seasonality"). Is it reasonable to allow feature registration to define tags for individual values of the output? That way `feature_set(tag = "seasonality")` would match `features_stl` but only return the computed values that are relevant to seasonality.

This may be difficult to implement, as the output of many features are not length stable.

**Comment by earowang** [comment]
Only functions can own tags.

**Comment by mitchelloharawild** [comment]
So is that a no? Keep things simple and have tags match entire feature functions?

**Comment by earowang** [comment]
Nope. If vector names follow standardised and good-practice naming, surely `contains(season)` is more intuitive to extract the features after computing. It's easy to look up functions not returned names.
