### ISSUE TITLE
Reconciliation interface

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/fablelite#84]
@earowang 
Could you share your opinions on the current reconciliation interface? I have just merged it into master in preparation of the CRAN release.

Things I'm considering are:
* changing the `method` argument in `MinT` to accept a function
* Prefixing `MinT` by some common prefix, as other reconciliation methods (`BU`, `MO` and `TD` are too short... alternatively these could be `bottom_up`, `middle_out`, `top_down`)
* Change the `mdls` argument to `lst_mdl`, or something more descriptive.

``` r
library(tsibble)
library(tidyverse)
library(fable)
#> Loading required package: fablelite
tourism_grp <- tourism %>% 
  aggregate_keys(State / Purpose, Trips = sum(Trips))

fit <- tourism_grp %>% 
  model(ETS = fable::ETS(Trips))

fc <- fit %>% 
  reconcile(Coherent = MinT(mdls = ETS, method = "ols", sparse = TRUE)) %>%
  forecast()
#> Note: reconciliation in fable is highly experimental. The interface will be refined in the near future.

fc %>% 
  filter(State == "Victoria") %>% 
  autoplot(tourism_grp, level = 95)
```

![](https://i.imgur.com/wLOHICS.png)

<sup>Created on 2019-06-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by earowang** [comment]
* split `aggregate_key`(s)?? into two steps:

```r
tourism %>% 
  reconcile_key_spec(~ (Region / State) * Purpose) %>%
  summarise(Trips = sum(Trips))
```
Featuring Wilkinson-Rogers formula interface. See https://github.com/tidyverse/tidyr/issues/448 and "The grammar of graphics" for details
1. `/` for nesting
2. `*` for crossing

* I assume these methods can only be called in `reconcile()`? No prefixing is fine, but not PascalCase `MinT`?
* `mdls` -> `models`

**Comment by mitchelloharawild** [comment]
I don't think it's correct to use `summarise()` as the verb in this context. The output structures are different, in that `aggregate_*()` computes the summary at all levels of the specified aggregation structure, whereas `summarise()` always reduces the structure of the data.

Regarding the formula interface `~ (Region / State) * Purpose`, that is correct and is how it is implemented in `aggregate_keys()` - I've just defined an incorrect structure (just copied from my testing of hierarchies without thinking of its meaning). To correctly aggregate the tourism data you would use: `aggregate_keys((Region / State) * Purpose, Trips = sum(Trips))`. I don't think the `~` is necessary here (other than potentially disambiguating the structure from aggregation methods... but I think it is clear enough).

In implementation, the `MinT` function just adds a class to the list of models. `reconcile()` is actually just `mutate()`. This may change in the future (if `reconcile` can have more functionality, https://github.com/tidyverts/fablelite/issues/58). PascalCase for `MinT` is chosen due to its naming in the literature.

**Comment by mitchelloharawild** [comment]
`mdls` -> `models` is good. In the docs I'll also clarify its usage more pragmatically.

**Comment by mitchelloharawild** [comment]
Does this address all of your concerns @earowang?

**Comment by earowang** [comment]
You may want to investigate more which direction is correct https://github.com/tidyverts/tsibble/issues/64

From the grammar of graphics, it is `Region / State`

**Comment by mitchelloharawild** [comment]
Surely it's better for a modelling package to be consistent with existing modelling interfaces.

**Comment by mitchelloharawild** [comment]
For clarification, above structure was incorrect. The current fablelite implementation has:
`aggregate_keys((State / Region) * Purpose, Trips = sum(Trips))`
