### ISSUE TITLE
Error running interpolation example

### ISSUE THREAD

**Issue by pbroberts** [tidyverts/fablelite#9]
From this page:  [https://tidyverts.github.io/tidy-forecasting-principles/methods.html](url)  I run the example:
olympic_running %>% 
  model(lm = TSLM(Time ~ trend())) %>% 
  interpolate(olympic_running)

I get this error:
Error: A mable must contain at least one model. To remove all models, first convert to a tibble with `as_tibble()`.

The backtrace says:> rlang::last_trace()
     x
  1. \-olympic_running %>% model(lm = TSLM(Time ~ trend())) %>% interpolate(olympic_running)
  2.   +-base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  3.   \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  4.     \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5.       \-global::`_fseq`(`_lhs`)
  6.         \-magrittr::freduce(value, `_function_list`)
  7.           +-base::withVisible(function_list[[k]](value))
  8.           \-function_list[[k]](value)
  9.             +-generics::interpolate(., olympic_running)
 10.             \-fablelite:::interpolate.mdl_df(., olympic_running)
 11.               \-`%>%`(...)
 12.                 +-base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
 13.                 \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
 14.                   \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
 15.                     \-fablelite:::`_fseq`(`_lhs`)
 16.                       \-magrittr::freduce(value, `_function_list`)
 17.                         \-function_list[[i]](value)
 18.                           +-dplyr::transmute(...)
 19.                           \-dplyr:::transmute.default(...)
 20.                             +-dplyr::select(out, one_of(keep))
 21.                             \-fablelite:::select.mdl_df(out, one_of(keep))

Here's my sessionInfo:
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
...
other attached packages:
[1] dplyr_0.8.0            ggplot2_3.1.0          tsibbledata_0.0.0.9000 tsibble_0.6.2.9000     fable_0.0.0.9100       fablelite_0.0.0.9100

**Comment by mitchelloharawild** [comment]
I can't reproduce this issue. Please try updating the packages and try again.
